import Link from "next/link";
import Image from "next/image";
import styles from "./Footer.module.css";
import { SITE_CONFIG } from "@/config/constants";

export default function Footer() {
  return (
    <footer className={styles.footer} id="contact">
      <div className={`container ${styles.footerTop}`}>
        <div className={styles.grid}>
          
          {/* Column 1: Logo and Welcome Text */}
          <div className={styles.col}>
            <div className={styles.logoWrapper}>
              <Image 
                src="https://tiger365id.in/wp-content/uploads/2024/09/tiger365id.in-logo.png"
                alt="Tiger365 ID Logo"
                width={80}
                height={80}
                className={styles.logoImg}
              />
              <span className={styles.logoText}>TIGER365ID.IN</span>
            </div>
            <p className={styles.desc}>
              Welcome to Tiger365, India's premier sports betting and casino platform. Register now for a secure, fast experience and access your dashboard through our login page.
            </p>
          </div>

          {/* Column 2: First Helpful Links */}
          <div className={styles.col}>
            <h4 className={styles.colTitle}>Helpful Links</h4>
            <ul className={styles.linksList}>
              <li><Link href="#home">Tiger365</Link></li>
              <li><a href={SITE_CONFIG.whatsappLink} target="_blank" rel="noopener noreferrer">Create Account</a></li>
              <li><a href={SITE_CONFIG.whatsappLink} target="_blank" rel="noopener noreferrer">Login</a></li>
              <li><a href={SITE_CONFIG.whatsappLink} target="_blank" rel="noopener noreferrer">Register</a></li>
              <li><a href={SITE_CONFIG.whatsappLink} target="_blank" rel="noopener noreferrer">Sign Up</a></li>
            </ul>
          </div>

          {/* Column 3: Second Helpful Links */}
          <div className={styles.col}>
            <h4 className={styles.colTitle}>Helpful Links</h4>
            <ul className={styles.linksList}>
              <li><Link href="#about">Terms and Conditions</Link></li>
              <li><Link href="#about">Privacy and Policy</Link></li>
              <li><a href={SITE_CONFIG.whatsappLink} target="_blank" rel="noopener noreferrer">Whatsapp Number</a></li>
              <li><a href={SITE_CONFIG.whatsappLink} target="_blank" rel="noopener noreferrer">Customer Care Number</a></li>
              <li><Link href="#faq">XML Sitemap</Link></li>
            </ul>
          </div>

          {/* Column 4: Warning Disclaimer Text */}
          <div className={styles.col}>
            <p className={styles.warningDesc}>
              Players are requested not to contact any untrusted sources for tiger365id.in accounts as this is an online site and they can only register independently without any agents. Only deposit through the account details generated by the system or provided by our official support team.
            </p>
          </div>

        </div>
      </div>

      <div className={styles.footerBottom}>
        <div className="container">
          <p className={styles.copyrightText}>
            Copyright &copy; tiger365id.in
          </p>
        </div>
      </div>
    </footer>
  );
}
